# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stage2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.distress_button = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it_distress())
        self.distress_button.setGeometry(QtCore.QRect(40, 240, 91, 81))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("distress.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.distress_button.setIcon(icon)
        self.distress_button.setIconSize(QtCore.QSize(91, 71))
        self.distress_button.setFlat(True)
        self.distress_button.setObjectName("distress_button")
        self.misery_button = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it_misery())
        self.misery_button.setGeometry(QtCore.QRect(180, 250, 71, 71))
        self.misery_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("misery.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.misery_button.setIcon(icon1)
        self.misery_button.setIconSize(QtCore.QSize(91, 71))
        self.misery_button.setFlat(True)
        self.misery_button.setObjectName("misery_button")
        self.sorrow_button = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it_sorrow())
        self.sorrow_button.setGeometry(QtCore.QRect(300, 240, 71, 71))
        self.sorrow_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("sorrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sorrow_button.setIcon(icon2)
        self.sorrow_button.setIconSize(QtCore.QSize(91, 71))
        self.sorrow_button.setFlat(True)
        self.sorrow_button.setObjectName("sorrow_button")
        self.contented_button = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it_contented())
        self.contented_button.setGeometry(QtCore.QRect(410, 240, 91, 71))
        self.contented_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("contentment.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contented_button.setIcon(icon3)
        self.contented_button.setIconSize(QtCore.QSize(91, 71))
        self.contented_button.setFlat(True)
        self.contented_button.setObjectName("contented_button")
        self.happy_button = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it_happy())
        self.happy_button.setGeometry(QtCore.QRect(530, 240, 91, 71))
        self.happy_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("pleasureORhappy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.happy_button.setIcon(icon4)
        self.happy_button.setIconSize(QtCore.QSize(91, 71))
        self.happy_button.setFlat(True)
        self.happy_button.setObjectName("happy_button")
        self.excited_button = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it_excited())
        self.excited_button.setGeometry(QtCore.QRect(660, 240, 81, 71))
        self.excited_button.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("excited.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.excited_button.setIcon(icon5)
        self.excited_button.setIconSize(QtCore.QSize(91, 71))
        self.excited_button.setFlat(True)
        self.excited_button.setObjectName("excited_button")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(670, 180, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(550, 190, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(410, 170, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 190, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 190, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.happy_label = QtWidgets.QLabel(self.centralwidget)
        self.happy_label.setGeometry(QtCore.QRect(50, 190, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.happy_label.setFont(font)
        self.happy_label.setObjectName("happy_label")
        self.emotion_show = QtWidgets.QLabel(self.centralwidget)
        self.emotion_show.setGeometry(QtCore.QRect(250, 400, 291, 101))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.emotion_show.setFont(font)
        self.emotion_show.setText("")
        self.emotion_show.setObjectName("emotion_show")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def press_it_distress(self):
        self.emotion_show.setText("distressed Today")  
    def press_it_misery(self):
        self.emotion_show.setText("Feeling miserable Today")      
    def press_it_sorrow(self):
        self.emotion_show.setText("Sad Today")    
    def press_it_contented(self):
        self.emotion_show.setText("Contented Today")    
    def press_it_happy(self):
        self.emotion_show.setText("happy Today")
    def press_it_excited(self):
        self.emotion_show.setText("Excited Today")
    





    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Excited"))
        self.label_4.setText(_translate("MainWindow", "Happy"))
        self.label_3.setText(_translate("MainWindow", "Contented"))
        self.label_2.setText(_translate("MainWindow", "Sorrow"))
        self.label.setText(_translate("MainWindow", "Misery"))
        self.happy_label.setText(_translate("MainWindow", "Distress"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
